### ISSUE TITLE
参数绑定写入数据报错Table already exists

### ISSUE THREAD

**Issue by xinhochen** [taosdata/taos-connector-jdbc#101]
TDEngine版本：3.0.3.1
taos-jdbcdriver版本：3.1.0
超级表建表语句：
`CREATE STABLE stable (ts TIMESTAMP, c1 NCHAR(20), c2 NCHAR(100), c3 NCHAR(20), c4 BIGINT) TAGS (t1 NCHAR(40));`
参数绑定写入数据代码片段：
```
String sql = "INSERT INTO ? USING stable TAGS (?) (ts,c1,c2,c3) VALUES(?,?,?,?)";
try (TSDBPreparedStatement pstmt = connection.prepareStatement(sql).unwrap(TSDBPreparedStatement.class)) {
    for (Map.Entry<String, List<DTO>> entry : map.entrySet()) {
        String t1 = entry.getKey();
        List<DTO> dtoList = entry.getValue();
        pstmt.setTableName("p_" + t1);
        pstmt.setTagNString(0, t1);
        int size = dtoList.size();
        ArrayList<Long> tsList = new ArrayList<>(size);
        ArrayList<String> c1List = new ArrayList<>(size);
        ArrayList<String> c2List = new ArrayList<>(size);
        ArrayList<String> c3List = new ArrayList<>(size);
        for (DTO dto : dtoList) {
            tsList.add(dto.getTs());
            c1List.add(dto.getC1());
            c2List.add(dto.getC2());
            c3List.add(dto.getC3());
        }
        pstmt.setTimestamp(0, tsList);
        pstmt.setNString(1, c1List, 20);
        pstmt.setNString(2, c2List, 100);
        pstmt.setNString(3, c3List, 20);
        pstmt.columnDataAddBatch();
    }
    pstmt.columnDataExecuteBatch();
}
```
报错信息：
```
java.sql.SQLException: TDengine ERROR (2350): failed to execute batch bind, reason: Table already exists
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:86)
	at com.taosdata.jdbc.TSDBJNIConnector.executeBatch(TSDBJNIConnector.java:300)
	at com.taosdata.jdbc.TSDBPreparedStatement.columnDataExecuteBatch(TSDBPreparedStatement.java:899)
```

**Comment by xinhochen** [comment]
问题找到了，是timestamp时间精度错了
