### ISSUE TITLE
Add quotes for table names in the AbstractDatabaseMetaData for getColumns and getPrimaryKeys

### ISSUE THREAD

**Issue by LonwoLonwo** [taosdata/taos-connector-jdbc#140]
Hello!

As a continuation of this ticket https://github.com/dbeaver/dbeaver/issues/22161

I can create tables with upper-case symbols using quotes. 
But I can't get columns/primary key info from the driver because of the error:

```
!ENTRY org.jkiss.dbeaver.model 4 0 2024-01-26 08:18:12.906
!MESSAGE TDengine ERROR (0x2603): sql: describe power.device_property_27NbfMsBLLa_d0000000001_e_1, desc: Table does not exist
!STACK 0
java.sql.SQLException: TDengine ERROR (0x2603): sql: describe power.device_property_27NbfMsBLLa_d0000000001_e_1, desc: Table does not exist
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:95)
	at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:97)
	at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:78)
	at com.taosdata.jdbc.rs.RestfulStatement.executeQuery(RestfulStatement.java:39)
	at com.taosdata.jdbc.AbstractDatabaseMetaData.getColumns(AbstractDatabaseMetaData.java:1098)
	at com.taosdata.jdbc.rs.RestfulDatabaseMetaData.getColumns(RestfulDatabaseMetaData.java:78)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getColumns(JDBCDatabaseMetaDataImpl.java:1152)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.prepareTableColumnLoadStatement(GenericMetaModel.java:708)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareChildrenStatement(TableCache.java:81)
```

Because you do not add quotes for tables in quotes:
https://github.com/taosdata/taos-connector-jdbc/blob/a635bafeaf0dd425255b1a34d0096af5eb1cd1e8/src/main/java/com/taosdata/jdbc/AbstractDatabaseMetaData.java#L1565

https://github.com/taosdata/taos-connector-jdbc/blob/a635bafeaf0dd425255b1a34d0096af5eb1cd1e8/src/main/java/com/taosdata/jdbc/AbstractDatabaseMetaData.java#L982

Different drivers read metadata in different ways, and I see that MySQL driver (as an example) adds quotes for object names:

![2024-01-26 10_29_26-DBeaver  C__Users_anvolka_work_DbeaverP_dbeaver-workspace-idea  - C__Users_anvol](https://github.com/taosdata/taos-connector-jdbc/assets/45152336/0f03afb6-3972-449e-9543-88a45d19d3d3)

**Comment by sheyanjie-qq** [comment]
this issue will be fixed in next version: 3.2.9
