### ISSUE TITLE
AbstractWSResultSet中dataHandleExecutor引起FETCH DATA TIME OUT错误

### ISSUE THREAD

**Issue by ReznovHuang** [taosdata/taos-connector-jdbc#183]
## 问题现象

JDBC驱动版本：`3.3.0`

服务器版本：`3.3.2.0`

现象：有一数据接入服务向时序库中大量写入数据，该服务运行正常；另有一业务服务需要读取数据进行展示，并会定时并发读取数据以整理每日报表。当进行一定量的并发读取后，程序开始不断出现FETCH DATA TIME OUT错误。参考日志如下：

```log
com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 6000, active 0, maxActive 32, creating 1, createElapseMillis 88838, createErrorCount 91
        at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1899)
        at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1504)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1484)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1469)
        at com.xxxx.xxxx.service.impl.XXServiceImpl.lambda$getXXReport$1(XXServiceImpl.java:577)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.sql.SQLException: TDengine ERROR (0x2350): FETCH DATA TIME OUT
        at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:95)
        at com.taosdata.jdbc.BlockData.waitTillOK(BlockData.java:234)
        at com.taosdata.jdbc.ws.AbstractWSResultSet.next(AbstractWSResultSet.java:145)
        at com.alibaba.druid.pool.ValidConnectionCheckerAdapter.execValidQuery(ValidConnectionCheckerAdapter.java:69)
        at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1482)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1819)
        at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2967)
```

## 问题分析

[AbstractWSResultSet.java](https://github.com/taosdata/taos-connector-jdbc/blob/main/src/main/java/com/taosdata/jdbc/ws/AbstractWSResultSet.java)

![image](https://github.com/user-attachments/assets/f2f47884-c095-4e05-af85-dafa7115c449)

在43行处，使用了一个 `commonPool`。之后从62行开始的submit，流程上是获得一个 `BlockData` ，然后判断传输是否成功和完成，没有完成的话就为blockData设置buffer，然后放到队列中等后续解析，并且会用 `dataHandleExecutor` （就是之前提到的那个 `commonPool` ）调用 `BlockData` 的 `handleData` 做解析。

[BlockData.java](https://github.com/taosdata/taos-connector-jdbc/blob/main/src/main/java/com/taosdata/jdbc/BlockData.java)

BlockData在构建的时候有：

```java
this.semaphore = new Semaphore(0);
```

后续主要有我们上面提到的 `handleData()` （在完成解析后会执行 `semaphore.release();` 予以释放）和 `waitTillOK()` 。`waitTillOK()` 在等待500秒后如果没能获取到锁（即之前的 `handleData()` 还没完成释放），就返回一开始提到的 `FETCH DATA TIME OUT` 错误。

于是会发现，如果 `handleData()` 一直在等待没有被执行（例如 `commonPool` 里进了几个大任务导致其他任务一直在等待），最后在等待500秒之后，还是会报  `FETCH DATA TIME OUT` 错误，尽管连接实际上没有任何问题。

考虑到通常会结合数据库连接池（例如Druid）来使用，会出现更严重的问题：连接池在使用 `validateQuery` 进行确认时发现无法进行成功确认，于是把连接全都干掉了；但是在新建连接时也没法使用 `validateQuery` 来确认成功，于是一直得不到可用的连接（就像文首日志中的 `active 0, maxActive 32, creating 1`，但永远无法create出来）。

可以理解在这里用 `commonPool` 的用意，但对于这种情况个人更倾向于安排一个独立的线程池来进行。如果 `commonPool` 里有一个读取失败一直在重试导致无法释放的任务，在这里就会造成死锁了。

## 临时方案

供目前遇到问题的读者参考的临时方案：

* 不要使用 `commonPool` 执行可能耗时较长的任务（注意 `CompletableFuture.runAsync` 之类的可能不自知的情况）
* 通过 `System.setProperty("java.util.concurrent.ForkJoinPool.common.parallelism", "32")` 这样的方式来调整 `commonPool` 的并行度（默认是逻辑CPU数量减1）

**Comment by sheyanjie-qq** [comment]
我们会考虑优化一下，确实在用户使用 commonPool 做阻塞任务会有这个问题。

**Comment by sheyanjie-qq** [comment]
3.40 已经做了优化，不再使用 commonPool
