### ISSUE TITLE
运行官方JDBCDemo

### ISSUE THREAD

**Issue by homeless2010** [taosdata/taos-connector-jdbc#56]
* taos service linux x86 3.0.1.7
* taos windows cline3.0.1.7
* jdbc-driver:3.0.2
* jdk8 异常：
Exception in thread "main" java.lang.NoSuchMethodError: setByteArray
	at com.taosdata.jdbc.TSDBJNIConnector.initImp(Native Method)
	at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:43)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:157)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at com.taosdata.example.JdbcDemo.init(JdbcDemo.java:44)
	at com.taosdata.example.JdbcDemo.main(JdbcDemo.java:24)

* jdk17异常：
Exception in thread "main" java.lang.NoSuchMethodError: Lcom/taosdata/jdbc/TSDBResultSetBlockData;.setByteArray(II[B)V
	at com.taosdata.jdbc.TSDBJNIConnector.initImp(Native Method)
	at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:43)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:157)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at com.taosdata.example.JdbcDemo.init(JdbcDemo.java:44)
	at com.taosdata.example.JdbcDemo.main(JdbcDemo.java:24)
initImp为native方法TSDBResultSetBlockData.setByteArray也存在，不知什么原因

**Comment by sangshuduo** [comment]
估计 Windows/system32 下有旧版本 taos.dll

**Comment by sheyanjie-qq** [comment]
close this issue for no further information
