### ISSUE TITLE
3.2.0版本启动就报错

### ISSUE THREAD

**Issue by codering** [taosdata/taos-connector-jdbc#90]
从 3.1.0 升级 到 3.2.0
```
Caused by: java.lang.NumberFormatException: For input string: "${project"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[na:na]
        at java.base/java.lang.Integer.parseInt(Integer.java:654) ~[na:na]
        at java.base/java.lang.Integer.parseInt(Integer.java:786) ~[na:na]
        at com.taosdata.jdbc.AbstractDatabaseMetaData.<clinit>(AbstractDatabaseMetaData.java:30) ~[taos-jdbcdriver-3.2.0.jar:na]

```

我想知道这类 break change 从哪里可以看到？是需要每个开发人员体验踩坑的乐趣吗？

**Comment by huolibo** [comment]
3.2.0 版本存在问题，可以升级至 3.2.1 版本。估计明天（5月9日）可以在 maven 仓库中发现。

**Comment by codering** [comment]
目前 3.2.1 可用
